2024-05-15 10:55:28,242 - INFO - Epoch 1/2
2024-05-15 10:55:28,242 - INFO - ----------
Traceback (most recent call last):
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 330, in <module>
    model_ft = train_model(model,optimizer_ft, exp_lr_scheduler, args.num_epochs, loss_func,  dataset_loader, dataset_sizes, wandb)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 114, in train_model
    loss=loss_func(features, labels)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 55, in <lambda>
    return lambda labels, features: CircleLossExp(scale=args.scale, margin=args.margin, similarity=args.similarity)(features, labels)
AttributeError: 'Namespace' object has no attribute 'scale'
Traceback (most recent call last):
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 330, in <module>
    model_ft = train_model(model,optimizer_ft, exp_lr_scheduler, args.num_epochs, loss_func,  dataset_loader, dataset_sizes, wandb)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 114, in train_model
    loss=loss_func(features, labels)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 55, in <lambda>
    return lambda labels, features: CircleLossExp(scale=args.scale, margin=args.margin, similarity=args.similarity)(features, labels)
AttributeError: 'Namespace' object has no attribute 'scale'