2024-05-05 00:30:24,563 - INFO - Epoch 1/2
2024-05-05 00:30:24,563 - INFO - ----------
2024-05-05 00:32:17,048 - INFO - Epoch 0/1 Train Loss: 21.1140 train_acc: 0.0000
2024-05-05 00:33:07,164 - INFO - Validation Loss: 19.9491 Acc: 0.0000
2024-05-05 00:33:07,164 - INFO - Epoch 2/2
2024-05-05 00:33:07,164 - INFO - ----------
2024-05-05 00:34:57,051 - INFO - Epoch 1/1 Train Loss: 20.6688 train_acc: 0.0000
2024-05-05 00:35:46,911 - INFO - Validation Loss: 19.8851 Acc: 0.0000
2024-05-05 00:35:46,911 - INFO - Training complete in 0.0 h 5.0 m 22.347278356552124 s
2024-05-05 00:35:46,911 - INFO - Best val Acc: 0.00%
Traceback (most recent call last):
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 317, in <module>
    acc = test_model(model_ft, dataset_loader, dataset_sizes,loss_func)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 219, in test_model
    avg_test_accuracy_topk = (100.0 * correct_topk_predictions / dataset_sizes["test"]).to("cpu").numpy().item()
AttributeError: 'float' object has no attribute 'to'
Traceback (most recent call last):
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 317, in <module>
    acc = test_model(model_ft, dataset_loader, dataset_sizes,loss_func)
  File "C:\Users\marie\Desktop\Sanfour\MFRS\models\models_train.py", line 219, in test_model
    avg_test_accuracy_topk = (100.0 * correct_topk_predictions / dataset_sizes["test"]).to("cpu").numpy().item()
AttributeError: 'float' object has no attribute 'to'